name: Run tests
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - uses: dschep/install-pipenv-action@v1
      - run: pipenv install --dev
      - run: make lint
      - run: make test
